class Camera < ActiveHash::Base
  self.data = [
    { id: 1, name: '任意で選択してください' },
    { id: 2, name: 'ニコン' },
    { id: 3, name: 'キャノン' },
    { id: 4, name: '富士フィルム' },
    { id: 5, name: 'ペンタックス' },
    { id: 6, name: 'ソニー' },
    { id: 7, name: 'コニカミノルタ' },
    { id: 8, name: 'パナソニック' },
    { id: 9, name: 'オリンパス' },
    { id: 10, name: 'リコー' },
    { id: 11, name: 'その他' },
    { id: 12, name: 'カシオ' },
    { id: 13, name: 'KDDI' },
    { id: 14, name: 'シャープ' },
    { id: 15, name: 'シグマ' },
    { id: 16, name: 'マミヤ' },
    { id: 17, name: 'ライカ' },
    { id: 18, name: 'エプソン' },
    { id: 19, name: 'KFE' },
    { id: 20, name: 'ミノックス' },
    { id: 21, name: 'ケンコー' },
    { id: 22, name: 'コダック' },
    { id: 23, name: 'コニカ' },
    { id: 24, name: 'ミノルタ' },
    { id: 25, name: 'ポラロイド' },
    { id: 26, name: 'ユニデン' },
    { id: 27, name: 'ローライ' },
    { id: 28, name: '京セラ' },
    { id: 29, name: 'サンヨー' },
    { id: 30, name: '日立' },
    { id: 31, name: 'コシナ' },
    { id: 32, name: 'NH JAPAN' },
    { id: 33, name: 'プロニカ' },
    { id: 34, name: 'コンタックス' },
    { id: 35, name: 'ハッセルブラッド' },
    { id: 36, name: 'フォクトレンダー' },
    { id: 37, name: 'フジカ' },
    { id: 38, name: 'ドコモ' },
    { id: 39, name: 'サムスン' },
    { id: 40, name: 'ビビカム' },
    { id: 41, name: '東芝' },
    { id: 42, name: 'ゾーランコーポレーション' },
    { id: 43, name: 'ノーリツ綱機' },
    { id: 44, name: 'ビクター' },
    { id: 45, name: 'ノキア' },
    { id: 46, name: 'トミー' },
    { id: 47, name: 'ボーダフォン' },
    { id: 48, name: 'HTC' },
    { id: 49, name: 'アップル' },
    { id: 50, name: 'ロモグラフィー' },
    { id: 51, name: 'リコーイメージング' },
    { id: 52, name: 'ファーウェイ' }
  ]
end
